version: '3'
services:
  nestjs-server:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"
    environment:
      - REDIS_SERVER=redis
